import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
export const supabase = createClient(SUPABASE_URL || '', SUPABASE_KEY || '');

const ADMIN_EMAIL = 'karimmohammedkadry@gmail.com';
const categories = { business:'الأعمال', education:'التعليم', health:'الصحة', productivity:'الإنتاجية', games:'الألعاب', tools:'الأدوات' };
let apps = [];
let currentUser = null;
let currentProfile = null;

function escapeHTML(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function toast(message,type='success'){let b=document.getElementById('codexToast');if(!b){b=document.createElement('div');b.id='codexToast';b.className='codex-toast';document.body.appendChild(b);}b.className=`codex-toast show ${type}`;b.textContent=message;clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>b.classList.remove('show'),2800);}
function formatFileSize(bytes){const n=Number(bytes)||0;if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;return `${(n/1024**3).toFixed(2)} GB`;}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v??'';}
function appIconMarkup(app,cls='app-icon'){return app.icon_url?`<div class="${cls} has-image"><img src="${escapeHTML(app.icon_url)}" alt="${escapeHTML(app.name)}" loading="lazy"></div>`:`<div class="${cls} ${escapeHTML(app.color||'blue')}">${escapeHTML(app.icon_text||'C')}</div>`;}
function fileBadgeMarkup(app){const fs=app.app_files||[];return `<div class="file-badges">${fs.map(f=>`<span>${f.platform==='windows'?'EXE':'APK'} · ${escapeHTML(formatFileSize(f.size_bytes))}</span>`).join('')}</div>`;}
function getFile(app,platform){return (app.app_files||[]).find(f=>f.platform===platform);}
function appSize(app){return formatFileSize((app.app_files||[]).reduce((n,f)=>n+Number(f.size_bytes||0),0));}
function platformName(app){const p=(app.app_files||[]).map(f=>f.platform);if(p.includes('windows')&&p.includes('android'))return 'Windows + Android';if(p.includes('android'))return 'Android';return 'Windows';}
function publicUrl(path){return supabase.storage.from('app-files').getPublicUrl(path).data.publicUrl;}

async function requireConfig(){if(!SUPABASE_URL||!SUPABASE_KEY){toast('أضف VITE_SUPABASE_URL و VITE_SUPABASE_PUBLISHABLE_KEY في ملف البيئة.','error');return false;}return true;}
async function loadSession(){const {data}=await supabase.auth.getSession();currentUser=data.session?.user||null;if(currentUser)await loadProfile();return currentUser;}
async function loadProfile(){if(!currentUser)return null;const {data,error}=await supabase.from('profiles').select('*').eq('id',currentUser.id).single();if(error){console.error(error);return null;}currentProfile=data;return data;}
async function isAdmin(){return currentProfile?.role==='admin';}
async function loadApps(){const {data,error}=await supabase.from('apps').select('*,app_files(*)').order('created_at',{ascending:false});if(error){toast('تعذر تحميل التطبيقات من Supabase.','error');console.error(error);return [];}apps=data||[];return apps;}

function setupNavbar(){
  const loginBtn=document.getElementById('loginBtn');
  if(loginBtn){
    // Keep login navigation native so it works even if Supabase/session initialization fails.
    loginBtn.href=currentUser?'account.html':'login.html';
    loginBtn.textContent=currentUser?(currentProfile?.name||'حسابي'):'تسجيل الدخول';
    loginBtn.onclick=null;
  }
  document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=logout);
  if(currentUser && currentProfile?.role==='admin') document.querySelectorAll('.nav-actions').forEach(n=>{if(!n.querySelector('[data-dashboard-link]'))n.insertAdjacentHTML('afterbegin','<a class="secondary-btn" data-dashboard-link href="dashboard.html">لوحة التحكم</a>');});
}
async function logout(){await supabase.auth.signOut();location.href='index.html';}
function showLoading(){const el=document.querySelector('.loading-screen');if(!el)return;setTimeout(()=>el.classList.add('hide'),650);}

function displayApps(list){const grid=document.getElementById('appsGrid');if(!grid)return;grid.innerHTML=list.length?list.map(a=>`<article class="app-card"><a class="app-card-link" href="app.html?id=${a.id}">${appIconMarkup(a)}<div class="app-card-content"><span>${escapeHTML(a.category_name)}</span><h3>${escapeHTML(a.name)}</h3><p>${escapeHTML(a.description)}</p><div class="app-meta"><span>v${escapeHTML(a.version)}</span><span>${escapeHTML(appSize(a))}</span></div>${fileBadgeMarkup(a)}</div></a></article>`).join(''):'<div class="empty-state">لا توجد تطبيقات مطابقة.</div>';}
function displayReleases(){const box=document.getElementById('releasesList');if(!box)return;box.innerHTML=apps.slice(0,4).map(a=>`<article class="release-card"><a href="app.html?id=${a.id}">${appIconMarkup(a,'release-icon')}<div><span>v${escapeHTML(a.version)}</span><h3>${escapeHTML(a.name)}</h3><p>${escapeHTML(a.description)}</p></div></a></article>`).join('');}
function filterHomeApps(){const q=(document.getElementById('searchInput')?.value||'').trim().toLowerCase();const active=document.querySelector('.category.active')?.dataset.category||'all';displayApps(apps.filter(a=>(active==='all'||a.category===active)&&[a.name,a.description,a.category_name].some(v=>String(v||'').toLowerCase().includes(q))));}

async function loadAppDetails(){const el=document.getElementById('detailsName');if(!el)return;const id=new URLSearchParams(location.search).get('id');const app=apps.find(a=>a.id===id);if(!app){el.textContent='التطبيق غير موجود';return;}setText('detailsName',app.name);setText('detailsDescription',app.description);setText('detailsCategory',app.category_name);setText('detailsRating',app.rating||'—');setText('detailsVersion',app.version);setText('detailsSize',appSize(app));setText('detailsPlatform',platformName(app));const icon=document.getElementById('detailsIcon');if(icon)icon.innerHTML=app.icon_url?`<img src="${escapeHTML(app.icon_url)}" alt="">`:`${escapeHTML(app.icon_text||'C')}`;const options=document.getElementById('downloadOptions');if(options){options.innerHTML=(app.app_files||[]).map(f=>`<a class="download-option" href="${escapeHTML(publicUrl(f.storage_path))}" download target="_blank">تحميل ${f.platform==='windows'?'Windows / EXE':'Android / APK'} · ${escapeHTML(formatFileSize(f.size_bytes))}</a>`).join('');const main=getFile(app,'windows')||getFile(app,'android');if(main)document.getElementById('downloadBtn')?.addEventListener('click',()=>{location.href=publicUrl(main.storage_path);});else if(app.download_url)document.getElementById('downloadBtn')?.addEventListener('click',()=>location.href=app.download_url);else document.getElementById('downloadBtn')?.setAttribute('disabled','true');}const similar=document.getElementById('similarApps');if(similar)similar.innerHTML=apps.filter(x=>x.id!==app.id&&x.category===app.category).slice(0,3).map(a=>`<article class="similar-app-card">${appIconMarkup(a)}<div class="similar-info"><h3>${escapeHTML(a.name)}</h3><p>${escapeHTML(a.category_name)}</p></div><a class="mini-btn" href="app.html?id=${a.id}">عرض</a></article>`).join('');}

function bindPasswordToggles(){document.querySelectorAll('[data-toggle-password]').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.togglePassword);if(!i)return;i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'👁':'🙈';});}
function showAuthMessage(message,type='error'){const e=document.getElementById('authMessage');if(e){e.textContent=message;e.className=`auth-message ${type}`;}}
async function setupAuth(){const login=document.getElementById('loginForm'),reg=document.getElementById('registerForm');if(!login&&!reg)return;bindPasswordToggles();login?.addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('loginEmail').value.trim().toLowerCase(),password=document.getElementById('loginPassword').value;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return showAuthMessage(error.message,'error');location.href='index.html';});reg?.addEventListener('submit',async e=>{e.preventDefault();const name=document.getElementById('registerName').value.trim(),email=document.getElementById('registerEmail').value.trim().toLowerCase(),password=document.getElementById('registerPassword').value,confirm=document.getElementById('registerConfirm').value;if(password.length<6)return showAuthMessage('كلمة المرور يجب أن تكون 6 أحرف على الأقل.','error');if(password!==confirm)return showAuthMessage('كلمتا المرور غير متطابقتين.','error');const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name}}});if(error)return showAuthMessage(error.message,'error');if(data.session)location.href='index.html';else showAuthMessage('تم إنشاء الحساب. راجع البريد الإلكتروني لتأكيد الحساب ثم سجّل الدخول.','success');});const sw=document.getElementById('switchAuth');sw?.addEventListener('click',e=>{e.preventDefault();login?.classList.toggle('hidden');reg?.classList.toggle('hidden');const register=!reg?.classList.contains('hidden');setText('authTitle',register?'إنشاء حساب':'تسجيل الدخول');setText('authDescription',register?'أنشئ حسابًا جديدًا في CODEX App Store.':'ادخل إلى حسابك للوصول إلى المتجر.');setText('switchText',register?'لديك حساب بالفعل؟ تسجيل الدخول':'ليس لديك حساب؟ إنشاء حساب');});}

async function setupAccount(){const formName=document.getElementById('accountNameForm');if(!formName)return;if(!currentUser){location.href='login.html';return;}bindPasswordToggles();setText('accountName',currentProfile?.name);setText('accountEmail',currentProfile?.email||currentUser.email);setText('accountRole',currentProfile?.role==='admin'?'Admin':'User');setText('accountCreated',currentProfile?.created_at?new Date(currentProfile.created_at).toLocaleDateString('ar-EG'):'—');setText('accountNameInput',currentProfile?.name);const n=document.getElementById('accountNameInput');if(n)n.value=currentProfile?.name||'';const em=document.getElementById('accountEmailInput');if(em)em.value=currentProfile?.email||currentUser.email||'';formName.onsubmit=async e=>{e.preventDefault();const name=n.value.trim();const {error}=await supabase.from('profiles').update({name,updated_at:new Date().toISOString()}).eq('id',currentUser.id);if(error)return toast(error.message,'error');await loadProfile();setupNavbar();toast('تم تحديث الاسم.');};document.getElementById('accountEmailForm')?.addEventListener('submit',async e=>{e.preventDefault();const email=em.value.trim().toLowerCase();const {error}=await supabase.auth.updateUser({email});if(error)return toast(error.message,'error');await supabase.from('profiles').update({email,updated_at:new Date().toISOString()}).eq('id',currentUser.id);toast('تم طلب تحديث الإيميل. قد تحتاج لتأكيده من بريدك الإلكتروني.');});document.getElementById('accountPasswordForm')?.addEventListener('submit',async e=>{e.preventDefault();const p=document.getElementById('newPassword').value,c=document.getElementById('confirmPassword').value;if(p.length<6)return toast('كلمة المرور الجديدة يجب أن تكون 6 أحرف على الأقل.','error');if(p!==c)return toast('كلمتا المرور غير متطابقتين.','error');const {error}=await supabase.auth.updateUser({password:p});if(error)return toast(error.message,'error');e.target.reset();toast('تم تغيير كلمة المرور.');});}

async function requireAdmin(){if(!(await isAdmin())){location.href='login.html';return false;}return true;}
async function uploadStorageFile(file,path){const {error}=await supabase.storage.from('app-files').upload(path,file,{upsert:true,contentType:file.type||'application/octet-stream'});if(error)throw error;return path;}
async function uploadIcon(file,appId){if(!file)return null;const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`icons/${appId}/${Date.now()}.${ext}`;await uploadStorageFile(file,path);return publicUrl(path);}
async function saveAppFile(appId,platform,file,existing){if(!file)return existing;const ext=(file.name.split('.').pop()||platform).toLowerCase();const path=`apps/${appId}/${platform}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}.${ext}`;await uploadStorageFile(file,path);if(existing)await supabase.storage.from('app-files').remove([existing.storage_path]);const row={app_id:appId,platform,file_name:file.name,storage_path:path,mime_type:file.type||'application/octet-stream',size_bytes:file.size};const {data,error}=await supabase.from('app_files').upsert(row,{onConflict:'app_id,platform'}).select().single();if(error)throw error;return data;}
async function createAppRecord(form){if(!(await requireAdmin()))return;const name=document.getElementById('newAppName').value.trim(),description=document.getElementById('newAppDescription').value.trim(),category=document.getElementById('newAppCategory').value,version=document.getElementById('newAppVersion').value.trim(),iconText=document.getElementById('newAppIcon').value.trim()||'C';const exe=document.getElementById('newAppExe')?.files?.[0],apk=document.getElementById('newAppApk')?.files?.[0],icon=document.getElementById('newAppIconFile')?.files?.[0];if(!exe&&!apk)return toast('ارفع EXE أو APK على الأقل.','error');const {data,error}=await supabase.from('apps').insert({name,description,category,category_name:categories[category],version,icon_text:iconText,created_by:currentUser.id}).select().single();if(error)return toast(error.message,'error');try{if(icon){const iconUrl=await uploadIcon(icon,data.id);await supabase.from('apps').update({icon_url:iconUrl}).eq('id',data.id);}if(exe)await saveAppFile(data.id,'windows',exe,null);if(apk)await saveAppFile(data.id,'android',apk,null);const {data:files}=await supabase.from('app_files').select('*').eq('app_id',data.id);await supabase.from('apps').update({total_size_bytes:(files||[]).reduce((n,f)=>n+Number(f.size_bytes||0),0),platform:(files||[]).length===2?'Windows + Android':(files||[])[0]?.platform==='android'?'Android':'Windows'}).eq('id',data.id);await refreshDashboard();form.reset();setText('newAppSize','سيتم حسابه تلقائيًا');setText('newAppPlatform','سيتم تحديده تلقائيًا');toast('تم رفع التطبيق إلى Supabase Storage.');}catch(err){await supabase.from('apps').delete().eq('id',data.id);toast(err.message||'فشل رفع الملفات.','error');}}
async function renderDashboard(){await loadApps();setText('totalApps',apps.length);const {count:usersCount}=await supabase.from('profiles').select('*',{count:'exact',head:true});const {count:adminsCount}=await supabase.from('profiles').select('*',{count:'exact',head:true}).eq('role','admin');setText('totalUsers',usersCount||0);setText('totalAdmins',adminsCount||0);const box=document.getElementById('adminAppsList');if(box)box.innerHTML=apps.map(a=>`<div class="admin-app-item">${appIconMarkup(a,'admin-app-icon')}<div class="admin-app-info"><strong>${escapeHTML(a.name)}</strong><span>${escapeHTML(a.category_name)} · v${escapeHTML(a.version)} · ${escapeHTML(appSize(a))} · ${escapeHTML(platformName(a))}</span>${fileBadgeMarkup(a)}</div><div class="admin-actions"><a class="mini-btn" href="app.html?id=${a.id}" target="_blank">فتح الصفحة</a><button class="mini-btn" data-edit-app="${a.id}" type="button">تعديل</button><button class="delete-app-btn" data-delete-app="${a.id}" type="button">حذف</button></div></div>`).join('');await renderUsers();}
async function renderUsers(){const box=document.getElementById('usersList');if(!box)return;const {data,error}=await supabase.from('profiles').select('*').order('created_at',{ascending:false});if(error)return toast(error.message,'error');box.innerHTML=(data||[]).map(u=>`<div class="user-item"><div class="user-avatar">${escapeHTML((u.name||'U').charAt(0))}</div><div class="user-info"><strong>${escapeHTML(u.name)}</strong><span>${escapeHTML(u.email||'')}</span><small>إنشاء: ${new Date(u.created_at).toLocaleDateString('ar-EG')}</small></div><span class="user-role">${u.role==='admin'?'ADMIN':'USER'}</span><div class="user-actions"><button class="mini-btn" data-reset-user="${u.id}" type="button">تغيير كلمة المرور</button>${u.id!==currentUser.id?`<button class="delete-user-btn" data-delete-user="${u.id}" type="button">حذف</button>`:''}</div></div>`).join('');}
async function refreshDashboard(){await renderDashboard();}
async function addAdmin(e){e.preventDefault();if(!(await requireAdmin()))return;const name=document.getElementById('adminNameInput').value.trim(),email=document.getElementById('adminEmailInput').value.trim().toLowerCase(),password=document.getElementById('adminPasswordInput').value,confirm=document.getElementById('adminPasswordConfirm').value;if(password.length<6||password!==confirm)return toast('تحقق من كلمة المرور (6 أحرف على الأقل).','error');const {data,error}=await supabase.functions.invoke('create-admin',{body:{name,email,password}});if(error||data?.error)return toast(data?.error||error?.message||'فشل إنشاء Admin.','error');e.target.reset();await renderDashboard();toast('تم إنشاء Admin جديد.');}
async function deleteUser(id){if(!confirm('هل تريد حذف هذا الحساب؟'))return;const {data,error}=await supabase.functions.invoke('admin-delete-user',{body:{userId:id}});if(error||data?.error)return toast(data?.error||error?.message||'فشل حذف المستخدم.','error');await renderDashboard();toast('تم حذف الحساب.');}
async function resetUserPassword(id){const pass=prompt('اكتب كلمة المرور الجديدة (6 أحرف على الأقل):');if(!pass)return;if(pass.length<6)return toast('كلمة المرور قصيرة.','error');const {data,error}=await supabase.functions.invoke('admin-reset-password',{body:{userId:id,password:pass}});if(error||data?.error)return toast(data?.error||error?.message||'فشل تغيير كلمة المرور.','error');toast('تم تغيير كلمة المرور بدون كشف القديمة.');}
async function deleteStorageFiles(app){const paths=(app.app_files||[]).map(f=>f.storage_path);if(app.icon_url){const marker='/app-files/';const i=app.icon_url.indexOf(marker);if(i>=0)paths.push(app.icon_url.slice(i+marker.length));}if(paths.length)await supabase.storage.from('app-files').remove(paths);}
function openAppEditor(id){const app=apps.find(a=>a.id===id),modal=document.getElementById('appEditModal');if(!app||!modal)return;modal.dataset.appId=id;for(const [n,v] of Object.entries({name:app.name,description:app.description,version:app.version,category:app.category,iconText:app.icon_text||'C',downloadUrl:app.download_url||''})){const el=modal.querySelector(`[name="${n}"]`);if(el)el.value=v;}const p=modal.querySelector('[data-icon-preview]');if(p)p.innerHTML=app.icon_url?`<img src="${escapeHTML(app.icon_url)}" alt="">`:`<span>${escapeHTML(app.icon_text||'C')}</span>`;modal.classList.add('open');}
async function updateApp(e){e.preventDefault();if(!(await requireAdmin()))return;const modal=document.getElementById('appEditModal'),id=modal.dataset.appId,app=apps.find(a=>a.id===id),data=new FormData(e.target);if(!app)return;const patch={name:String(data.get('name')).trim(),description:String(data.get('description')).trim(),version:String(data.get('version')).trim(),category:String(data.get('category')),category_name:categories[String(data.get('category'))],icon_text:String(data.get('iconText')).trim()||'C',download_url:String(data.get('downloadUrl')).trim()||null,updated_at:new Date().toISOString()};const icon=e.target.querySelector('[name="iconFile"]')?.files?.[0];if(icon)patch.icon_url=await uploadIcon(icon,id);const {error}=await supabase.from('apps').update(patch).eq('id',id);if(error)return toast(error.message,'error');for(const [platform,field] of [['windows','exeFile'],['android','apkFile']]){const f=e.target.querySelector(`[name="${field}"]`)?.files?.[0];if(f)await saveAppFile(id,platform,f,getFile(app,platform));}const {data:files}=await supabase.from('app_files').select('*').eq('app_id',id);await supabase.from('apps').update({total_size_bytes:(files||[]).reduce((n,f)=>n+Number(f.size_bytes||0),0),platform:(files||[]).length===2?'Windows + Android':(files||[])[0]?.platform==='android'?'Android':'Windows'}).eq('id',id);modal.classList.remove('open');e.target.reset();await renderDashboard();toast('تم حفظ تحديث التطبيق والملفات.');}
async function setupDashboard(){if(!document.getElementById('addAppForm'))return;if(!(await requireAdmin()))return;document.getElementById('addAppForm').onsubmit=e=>{e.preventDefault();createAppRecord(e.target);};document.getElementById('addAdminForm')?.addEventListener('submit',addAdmin);document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>document.getElementById('appEditModal')?.classList.remove('open'));document.getElementById('appEditForm')?.addEventListener('submit',updateApp);await renderDashboard();}
function setupDashboardDelegation(){document.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-app]');if(edit)return openAppEditor(edit.dataset.editApp);const del=e.target.closest('[data-delete-app]');if(del){const app=apps.find(a=>a.id===del.dataset.deleteApp);if(!app||!confirm(`حذف "${app.name}" وملفاته؟`))return;await deleteStorageFiles(app);const {error}=await supabase.from('apps').delete().eq('id',app.id);if(error)return toast(error.message,'error');await renderDashboard();toast('تم حذف التطبيق.');}const du=e.target.closest('[data-delete-user]');if(du)await deleteUser(du.dataset.deleteUser);const rp=e.target.closest('[data-reset-user]');if(rp)await resetUserPassword(rp.dataset.resetUser);});}
function setupUploadPreviews(){const exe=document.getElementById('newAppExe'),apk=document.getElementById('newAppApk'),size=document.getElementById('newAppSize'),platform=document.getElementById('newAppPlatform');const update=()=>{const files=[exe?.files?.[0],apk?.files?.[0]].filter(Boolean);if(size)setText('newAppSize',formatFileSize(files.reduce((n,f)=>n+f.size,0)));if(platform)setText('newAppPlatform',files.length===2?'Windows + Android':files[0]?.name.toLowerCase().endsWith('.apk')?'Android':'Windows');};exe?.addEventListener('change',update);apk?.addEventListener('change',update);document.getElementById('newAppIconFile')?.addEventListener('change',e=>{const l=document.querySelector('[data-file-label="icon"]');if(l)l.textContent=e.target.files?.[0]?.name||'PNG / JPG / WEBP';});}

(async()=>{
  // Bind navigation and page-local auth handlers first. Navigation must not depend on async Supabase calls.
  setupNavbar();
  await setupAuth();
  setupAccount();
  setupUploadPreviews();

  const configReady=await requireConfig();
  if(configReady){
    try{
      await loadSession();
      setupNavbar();
      if(document.getElementById('addAppForm')) await setupDashboard();
      setupDashboardDelegation();
      if(document.getElementById('appsGrid') || document.getElementById('releasesList') || document.getElementById('detailsName')){
        await loadApps();
        displayApps(apps);
        displayReleases();
        await loadAppDetails();
      }
    }catch(err){
      console.error('CODEX initialization error:',err);
    }
  }

  document.getElementById('searchInput')?.addEventListener('input',filterHomeApps);
  document.getElementById('searchBtn')?.addEventListener('click',filterHomeApps);
  document.querySelectorAll('.category').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');filterHomeApps();}));
  showLoading();
})();
